---
- hosts: webserver
  become: true
  become_user: root
  tasks:
    - name: Installing the multiple packages
      apt:
        name: "{{item}}"
        state: present
      loop:
        - nginx
        - tree
        - git
    - name: starting the nginx service
      service:
        name: nginx
        state: started
